# Generated by Django 2.2.10 on 2020-06-10 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    replaces = [('tfat', '0001_initial'), ('tfat', '0002_auto_20200220_0949'), ('tfat', '0003_auto_20200220_1242'), ('tfat', '0004_auto_20200220_1647'), ('tfat', '0005_auto_20200220_1718'), ('tfat', '0006_auto_20200221_1652'), ('tfat', '0007_auto_20200224_1338'), ('tfat', '0008_auto_20200415_1940'), ('tfat', '0009_auto_20200415_2001'), ('tfat', '0010_auto_20200415_2103'), ('tfat', '0011_auto_20200415_2158'), ('tfat', '0012_auto_20200415_2224'), ('tfat', '0013_auto_20200416_1012'), ('tfat', '0014_auto_20200416_1049'), ('tfat', '0015_upload_to_tfat_tag_reports')]

    dependencies = [
        ('common', '0001_initial'),
        ('common', '0003_auto_20200414_1700'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_database', models.CharField(max_length=250)),
                ('path', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Master Database',
            },
        ),
        migrations.CreateModel(
            name='JoePublic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=50)),
                ('initial', models.CharField(blank=True, max_length=5, null=True)),
                ('address1', models.CharField(blank=True, max_length=50, null=True)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('town', models.CharField(blank=True, max_length=50, null=True)),
                ('province', models.CharField(blank=True, choices=[('ON', 'Ontario'), ('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NS', 'Nova Scotia'), ('NT', 'Northwest Territories'), ('NU', 'Nunavut'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon'), ('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=12, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=7, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Recovery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recovery_date', models.DateField(blank=True, null=True)),
                ('date_flag', models.IntegerField(choices=[(2, 'Derived'), (0, 'Unknown'), (1, 'Reported')], default=1, verbose_name='Date Flag')),
                ('general_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='General Location')),
                ('specific_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Specific Location')),
                ('dd_lat', models.FloatField(blank=True, null=True)),
                ('dd_lon', models.FloatField(blank=True, null=True)),
                ('latlon_flag', models.IntegerField(choices=[(2, 'Derived'), (0, 'Unknown'), (1, 'Reported')], default=1, verbose_name='Spatial Flag')),
                ('spatial_followup', models.BooleanField(default=False)),
                ('flen', models.IntegerField(blank=True, null=True, verbose_name='Fork Length')),
                ('tlen', models.IntegerField(blank=True, null=True, verbose_name='Total Length')),
                ('rwt', models.IntegerField(blank=True, null=True, verbose_name='Round Weight')),
                ('girth', models.IntegerField(blank=True, null=True, verbose_name='Girth')),
                ('sex', models.CharField(blank=True, choices=[('1', 'Male'), ('3', 'Hermaphrodite'), ('9', 'Unknown'), ('2', 'Female')], default='9', max_length=3, null=True, verbose_name='Sex')),
                ('clipc', models.CharField(blank=True, max_length=5, null=True, verbose_name='Clip Code')),
                ('tagid', models.CharField(db_index=True, max_length=20)),
                ('_tag_origin', models.CharField(choices=[('10', 'Lakehead University'), ('98', 'Other'), ('24', 'CORA'), ('05', 'University of Toronto'), ('20', 'USGS'), ('09', 'State of Minnesota'), ('07', 'State of Pennsylvania'), ('13', 'Ontario Hydro'), ('19', 'USFWS'), ('02', 'New York State'), ('25', 'AOFRC'), ('11', 'Sir Sandford Fleming College'), ('06', 'State of Ohio'), ('08', 'Royal Ontario Museum'), ('26', 'GLLFAS'), ('01', 'Ontario Ministry of Natural Resources'), ('03', 'State of Michigan'), ('99', 'Unknown'), ('12', 'Private Club'), ('04', 'University of Guelph')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin')),
                ('_tag_position', models.CharField(choices=[('6', 'Jaw'), ('8', 'Anal'), ('4', 'Abdominal Insertion'), ('2', 'Between Dorsal'), ('5', 'Flesh of Back'), ('1', 'Anterior Dorsal'), ('3', 'Posterior Dorsal'), ('7', 'Snout'), ('9', 'Unknown')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position')),
                ('_tag_type', models.CharField(choices=[('B', 'Metal Livestock'), ('1', 'Streamer'), ('6', 'Coded Wire'), ('7', 'Strip Vinyl  '), ('2', 'Tubular Vinyl'), ('A', 'Internal (Radio)'), ('5', 'Anchor'), ('8', 'Secure Tie'), ('C', 'Cinch'), ('P', 'PIT tag'), ('3', 'Circular Strap Jaw '), ('4', 'Butt End Jaw ')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type')),
                ('_tag_colour', models.CharField(choices=[('3', 'Red'), ('5', 'Orange'), ('7', 'White'), ('4', 'Green'), ('1', 'Colourless'), ('2', 'Yellow'), ('6', 'Silver'), ('9', 'Unknown')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour')),
                ('tagdoc', models.CharField(db_index=True, default='25012', max_length=6, verbose_name='TAGDOC')),
                ('tag_removed', models.BooleanField(default=False)),
                ('fate', models.CharField(blank=True, choices=[('R', 'Released'), ('K', 'Killed')], default='R', max_length=3, null=True, verbose_name='Fate')),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('lake', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='common.Lake')),
            ],
            options={
                'ordering': ['tagdoc', 'tagid'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(blank=True, null=True, verbose_name='Report Date')),
                ('date_flag', models.IntegerField(choices=[(2, 'Derived'), (1, 'Reported'), (0, 'Unknown')], default=0, verbose_name='Date Flag')),
                ('reporting_format', models.CharField(choices=[('letter', 'letter'), ('other', 'other'), ('dcr', 'DCR'), ('verbal', 'verbal'), ('e-mail', 'e-mail')], default='verbal', max_length=30, verbose_name='Report Format')),
                ('dcr', models.CharField(blank=True, max_length=15, null=True)),
                ('effort', models.CharField(blank=True, max_length=15, null=True)),
                ('associated_file', models.FileField(blank=True, null=True, upload_to='reports')),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('follow_up', models.BooleanField(default=False)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reported_By', to='tfat.JoePublic')),
            ],
            options={
                'verbose_name_plural': 'JoePublic',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_code', models.IntegerField(unique=True)),
                ('common_name', models.CharField(max_length=40)),
                ('scientific_name', models.CharField(blank=True, max_length=50, null=True)),
                ('primary', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Species',
                'ordering': ['-primary', 'common_name'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.FileField(upload_to='tag_return_letters/')),
                ('zoom', models.IntegerField(blank=True, null=True, verbose_name='Map Zoom')),
                ('method', models.CharField(choices=[('custom_letter', 'Custom Letter'), ('tfat_template', 'TFAT Template')], default='tfat_template', max_length=30, verbose_name='Generated By')),
                ('recovery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_letters', to='tfat.Recovery')),
            ],
        ),
        migrations.AddField(
            model_name='recovery',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Report', to='tfat.Report'),
        ),
        migrations.AddField(
            model_name='recovery',
            name='spc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='tfat.Species'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('prj_cd', models.CharField(db_index=True, max_length=12)),
                ('prj_nm', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('dbase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfat.Database')),
                ('lake', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Projects', to='common.Lake')),
            ],
            options={
                'ordering': ['-year', 'prj_cd'],
            },
        ),
        migrations.AlterIndexTogether(
            name='recovery',
            index_together={('tagid', 'tagdoc', 'spc')},
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('2', 'Yellow'), ('7', 'White'), ('9', 'Unknown'), ('3', 'Red'), ('4', 'Green'), ('6', 'Silver'), ('1', 'Colourless'), ('5', 'Orange')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('01', 'Ontario Ministry of Natural Resources'), ('99', 'Unknown'), ('20', 'USGS'), ('03', 'State of Michigan'), ('11', 'Sir Sandford Fleming College'), ('19', 'USFWS'), ('12', 'Private Club'), ('09', 'State of Minnesota'), ('98', 'Other'), ('06', 'State of Ohio'), ('05', 'University of Toronto'), ('26', 'GLLFAS'), ('08', 'Royal Ontario Museum'), ('02', 'New York State'), ('25', 'AOFRC'), ('10', 'Lakehead University'), ('07', 'State of Pennsylvania'), ('04', 'University of Guelph'), ('24', 'CORA'), ('13', 'Ontario Hydro')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('2', 'Between Dorsal'), ('9', 'Unknown'), ('1', 'Anterior Dorsal'), ('6', 'Jaw'), ('3', 'Posterior Dorsal'), ('5', 'Flesh of Back'), ('7', 'Snout'), ('4', 'Abdominal Insertion'), ('8', 'Anal')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('2', 'Tubular Vinyl'), ('C', 'Cinch'), ('8', 'Secure Tie'), ('3', 'Circular Strap Jaw '), ('B', 'Metal Livestock'), ('P', 'PIT tag'), ('1', 'Streamer'), ('5', 'Anchor'), ('7', 'Strip Vinyl  '), ('4', 'Butt End Jaw '), ('A', 'Internal (Radio)'), ('6', 'Coded Wire')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='date_flag',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Reported'), (2, 'Derived')], default=1, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='latlon_flag',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Reported'), (2, 'Derived')], default=1, verbose_name='Spatial Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, choices=[('2', 'Female'), ('3', 'Hermaphrodite'), ('9', 'Unknown'), ('1', 'Male')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('1', 'Colourless'), ('2', 'Yellow'), ('5', 'Orange'), ('7', 'White'), ('9', 'Unknown'), ('4', 'Green'), ('3', 'Red'), ('6', 'Silver')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('19', 'USFWS'), ('01', 'Ontario Ministry of Natural Resources'), ('25', 'AOFRC'), ('07', 'State of Pennsylvania'), ('06', 'State of Ohio'), ('20', 'USGS'), ('98', 'Other'), ('04', 'University of Guelph'), ('26', 'GLLFAS'), ('09', 'State of Minnesota'), ('05', 'University of Toronto'), ('10', 'Lakehead University'), ('24', 'CORA'), ('99', 'Unknown'), ('12', 'Private Club'), ('08', 'Royal Ontario Museum'), ('02', 'New York State'), ('11', 'Sir Sandford Fleming College'), ('03', 'State of Michigan'), ('13', 'Ontario Hydro')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('6', 'Jaw'), ('5', 'Flesh of Back'), ('1', 'Anterior Dorsal'), ('8', 'Anal'), ('9', 'Unknown'), ('4', 'Abdominal Insertion'), ('7', 'Snout'), ('3', 'Posterior Dorsal'), ('2', 'Between Dorsal')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('3', 'Circular Strap Jaw '), ('P', 'PIT tag'), ('4', 'Butt End Jaw '), ('B', 'Metal Livestock'), ('C', 'Cinch'), ('6', 'Coded Wire'), ('A', 'Internal (Radio)'), ('1', 'Streamer'), ('8', 'Secure Tie'), ('5', 'Anchor'), ('7', 'Strip Vinyl  '), ('2', 'Tubular Vinyl')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='date_flag',
            field=models.IntegerField(choices=[(1, 'Reported'), (0, 'Unknown'), (2, 'Derived')], default=1, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='latlon_flag',
            field=models.IntegerField(choices=[(1, 'Reported'), (0, 'Unknown'), (2, 'Derived')], default=1, verbose_name='Spatial Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, choices=[('3', 'Hermaphrodite'), ('1', 'Male'), ('9', 'Unknown'), ('2', 'Female')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sam', models.CharField(max_length=5)),
                ('eff', models.CharField(max_length=3)),
                ('grp', models.CharField(max_length=3)),
                ('fish', models.CharField(max_length=10)),
                ('observation_date', models.DateField()),
                ('grid', models.CharField(max_length=4)),
                ('dd_lat', models.FloatField()),
                ('dd_lon', models.FloatField()),
                ('flen', models.IntegerField(blank=True, null=True)),
                ('tlen', models.IntegerField(blank=True, null=True)),
                ('rwt', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Hermaphrodite'), ('9', 'Unknown')], default='9', max_length=3, null=True, verbose_name='Sex')),
                ('clipc', models.CharField(blank=True, max_length=5, null=True)),
                ('tagid', models.CharField(db_index=True, max_length=20)),
                ('tagdoc', models.CharField(blank=True, db_index=True, max_length=6, null=True)),
                ('tagstat', models.CharField(blank=True, choices=[('A', 'Applied'), ('C', 'Existed on Capture')], db_index=True, default='C', max_length=4, null=True)),
                ('fate', models.CharField(blank=True, choices=[('R', 'Released'), ('K', 'Killed')], default='C', max_length=2, null=True)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Encounters', to='tfat.Project')),
                ('spc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfat.Species')),
            ],
            options={
                'ordering': ['tagdoc', 'tagid', 'observation_date'],
                'index_together': {('tagid', 'tagdoc', 'spc')},
            },
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('1', 'Colourless'), ('6', 'Silver'), ('9', 'Unknown'), ('5', 'Orange'), ('4', 'Green'), ('2', 'Yellow'), ('7', 'White'), ('3', 'Red')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('11', 'Sir Sandford Fleming College'), ('01', 'Ontario Ministry of Natural Resources'), ('09', 'State of Minnesota'), ('10', 'Lakehead University'), ('12', 'Private Club'), ('04', 'University of Guelph'), ('25', 'AOFRC'), ('26', 'GLLFAS'), ('03', 'State of Michigan'), ('06', 'State of Ohio'), ('99', 'Unknown'), ('20', 'USGS'), ('05', 'University of Toronto'), ('24', 'CORA'), ('07', 'State of Pennsylvania'), ('02', 'New York State'), ('98', 'Other'), ('13', 'Ontario Hydro'), ('08', 'Royal Ontario Museum'), ('19', 'USFWS')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('9', 'Unknown'), ('2', 'Between Dorsal'), ('8', 'Anal'), ('5', 'Flesh of Back'), ('7', 'Snout'), ('4', 'Abdominal Insertion'), ('1', 'Anterior Dorsal'), ('3', 'Posterior Dorsal'), ('6', 'Jaw')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('5', 'Anchor'), ('C', 'Cinch'), ('4', 'Butt End Jaw '), ('3', 'Circular Strap Jaw '), ('A', 'Internal (Radio)'), ('7', 'Strip Vinyl  '), ('6', 'Coded Wire'), ('8', 'Secure Tie'), ('P', 'PIT tag'), ('B', 'Metal Livestock'), ('2', 'Tubular Vinyl'), ('1', 'Streamer')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Hermaphrodite'), ('9', 'Unknown')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('1', 'Colourless'), ('4', 'Green'), ('9', 'Unknown'), ('3', 'Red'), ('7', 'White'), ('2', 'Yellow'), ('5', 'Orange'), ('6', 'Silver')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('12', 'Private Club'), ('05', 'University of Toronto'), ('10', 'Lakehead University'), ('25', 'AOFRC'), ('99', 'Unknown'), ('08', 'Royal Ontario Museum'), ('24', 'CORA'), ('09', 'State of Minnesota'), ('02', 'New York State'), ('11', 'Sir Sandford Fleming College'), ('03', 'State of Michigan'), ('07', 'State of Pennsylvania'), ('01', 'Ontario Ministry of Natural Resources'), ('19', 'USFWS'), ('26', 'GLLFAS'), ('04', 'University of Guelph'), ('13', 'Ontario Hydro'), ('20', 'USGS'), ('06', 'State of Ohio'), ('98', 'Other')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('2', 'Between Dorsal'), ('7', 'Snout'), ('9', 'Unknown'), ('3', 'Posterior Dorsal'), ('1', 'Anterior Dorsal'), ('8', 'Anal'), ('4', 'Abdominal Insertion'), ('6', 'Jaw'), ('5', 'Flesh of Back')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('P', 'PIT tag'), ('4', 'Butt End Jaw '), ('1', 'Streamer'), ('5', 'Anchor'), ('B', 'Metal Livestock'), ('C', 'Cinch'), ('7', 'Strip Vinyl  '), ('3', 'Circular Strap Jaw '), ('6', 'Coded Wire'), ('A', 'Internal (Radio)'), ('2', 'Tubular Vinyl'), ('8', 'Secure Tie')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='date_flag',
            field=models.IntegerField(choices=[(2, 'Derived'), (1, 'Reported'), (0, 'Unknown')], default=1, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='latlon_flag',
            field=models.IntegerField(choices=[(2, 'Derived'), (1, 'Reported'), (0, 'Unknown')], default=1, verbose_name='Spatial Flag'),
        ),
        migrations.CreateModel(
            name='ReportFollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('initialized', 'Initialized'), ('completed', 'Completed')], db_index=True, default='requested', max_length=12, verbose_name='Follow Up Status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='tfat.Report')),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('id', 'status')},
            },
        ),
        migrations.AddConstraint(
            model_name='reportfollowup',
            constraint=models.UniqueConstraint(fields=('id', 'status'), name='unique status'),
        ),
        migrations.RemoveConstraint(
            model_name='reportfollowup',
            name='unique status',
        ),
        migrations.AlterField(
            model_name='encounter',
            name='sex',
            field=models.CharField(blank=True, choices=[('2', 'Female'), ('1', 'Male'), ('9', 'Unknown'), ('3', 'Hermaphrodite')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('9', 'Unknown'), ('3', 'Red'), ('5', 'Orange'), ('7', 'White'), ('4', 'Green'), ('1', 'Colourless'), ('6', 'Silver'), ('2', 'Yellow')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('20', 'USGS'), ('04', 'University of Guelph'), ('06', 'State of Ohio'), ('12', 'Private Club'), ('10', 'Lakehead University'), ('05', 'University of Toronto'), ('19', 'USFWS'), ('11', 'Sir Sandford Fleming College'), ('02', 'New York State'), ('25', 'AOFRC'), ('09', 'State of Minnesota'), ('24', 'CORA'), ('08', 'Royal Ontario Museum'), ('01', 'Ontario Ministry of Natural Resources'), ('03', 'State of Michigan'), ('26', 'GLLFAS'), ('13', 'Ontario Hydro'), ('99', 'Unknown'), ('07', 'State of Pennsylvania'), ('98', 'Other')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('1', 'Anterior Dorsal'), ('8', 'Anal'), ('3', 'Posterior Dorsal'), ('9', 'Unknown'), ('4', 'Abdominal Insertion'), ('6', 'Jaw'), ('7', 'Snout'), ('2', 'Between Dorsal'), ('5', 'Flesh of Back')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('C', 'Cinch'), ('7', 'Strip Vinyl  '), ('8', 'Secure Tie'), ('5', 'Anchor'), ('4', 'Butt End Jaw '), ('A', 'Internal (Radio)'), ('6', 'Coded Wire'), ('B', 'Metal Livestock'), ('1', 'Streamer'), ('2', 'Tubular Vinyl'), ('P', 'PIT tag'), ('3', 'Circular Strap Jaw ')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='date_flag',
            field=models.IntegerField(choices=[(1, 'Reported'), (2, 'Derived'), (0, 'Unknown')], default=1, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='latlon_flag',
            field=models.IntegerField(choices=[(1, 'Reported'), (2, 'Derived'), (0, 'Unknown')], default=1, verbose_name='Spatial Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='tfat.Report'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, choices=[('2', 'Female'), ('1', 'Male'), ('9', 'Unknown'), ('3', 'Hermaphrodite')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_flag',
            field=models.IntegerField(choices=[(1, 'Reported'), (2, 'Derived'), (0, 'Unknown')], default=0, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_format',
            field=models.CharField(choices=[('e-mail', 'e-mail'), ('other', 'other'), ('dcr', 'DCR'), ('verbal', 'verbal'), ('letter', 'letter')], default='verbal', max_length=30, verbose_name='Report Format'),
        ),
        migrations.AlterUniqueTogether(
            name='reportfollowup',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='reportfollowup',
            constraint=models.UniqueConstraint(fields=('report', 'status'), name='unique report_status'),
        ),
        migrations.AddField(
            model_name='report',
            name='follow_up_status',
            field=models.CharField(blank=True, choices=[('requested', 'Requested'), ('initialized', 'Initialized'), ('completed', 'Completed')], db_index=True, default=None, max_length=12, null=True, verbose_name='Follow Up Status'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='sex',
            field=models.CharField(blank=True, choices=[('3', 'Hermaphrodite'), ('2', 'Female'), ('1', 'Male'), ('9', 'Unknown')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('7', 'White'), ('6', 'Silver'), ('5', 'Orange'), ('9', 'Unknown'), ('3', 'Red'), ('4', 'Green'), ('2', 'Yellow'), ('1', 'Colourless')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('09', 'State of Minnesota'), ('07', 'State of Pennsylvania'), ('12', 'Private Club'), ('01', 'Ontario Ministry of Natural Resources'), ('19', 'USFWS'), ('98', 'Other'), ('08', 'Royal Ontario Museum'), ('11', 'Sir Sandford Fleming College'), ('25', 'AOFRC'), ('02', 'New York State'), ('20', 'USGS'), ('03', 'State of Michigan'), ('06', 'State of Ohio'), ('26', 'GLLFAS'), ('99', 'Unknown'), ('24', 'CORA'), ('13', 'Ontario Hydro'), ('04', 'University of Guelph'), ('10', 'Lakehead University'), ('05', 'University of Toronto')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('6', 'Jaw'), ('9', 'Unknown'), ('2', 'Between Dorsal'), ('8', 'Anal'), ('5', 'Flesh of Back'), ('4', 'Abdominal Insertion'), ('3', 'Posterior Dorsal'), ('7', 'Snout'), ('1', 'Anterior Dorsal')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('3', 'Circular Strap Jaw '), ('7', 'Strip Vinyl  '), ('P', 'PIT tag'), ('5', 'Anchor'), ('4', 'Butt End Jaw '), ('1', 'Streamer'), ('A', 'Internal (Radio)'), ('B', 'Metal Livestock'), ('2', 'Tubular Vinyl'), ('C', 'Cinch'), ('8', 'Secure Tie'), ('6', 'Coded Wire')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='date_flag',
            field=models.IntegerField(choices=[(0, 'Unknown'), (2, 'Derived'), (1, 'Reported')], default=1, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='latlon_flag',
            field=models.IntegerField(choices=[(0, 'Unknown'), (2, 'Derived'), (1, 'Reported')], default=1, verbose_name='Spatial Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, choices=[('3', 'Hermaphrodite'), ('2', 'Female'), ('1', 'Male'), ('9', 'Unknown')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_flag',
            field=models.IntegerField(choices=[(0, 'Unknown'), (2, 'Derived'), (1, 'Reported')], default=0, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_format',
            field=models.CharField(choices=[('letter', 'letter'), ('verbal', 'verbal'), ('e-mail', 'e-mail'), ('other', 'other'), ('dcr', 'DCR')], default='verbal', max_length=30, verbose_name='Report Format'),
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-report_date']},
        ),
        migrations.AlterField(
            model_name='encounter',
            name='sex',
            field=models.CharField(blank=True, choices=[('2', 'Female'), ('1', 'Male'), ('3', 'Hermaphrodite'), ('9', 'Unknown')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='tagstat',
            field=models.CharField(blank=True, choices=[('C', 'Existed on Capture'), ('A', 'Applied')], db_index=True, default='C', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('9', 'Unknown'), ('5', 'Orange'), ('2', 'Yellow'), ('3', 'Red'), ('7', 'White'), ('1', 'Colourless'), ('4', 'Green'), ('6', 'Silver')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('01', 'MNRF'), ('08', 'ROM'), ('10', 'Lakehead'), ('02', 'NY'), ('03', 'Mich.'), ('25', 'AOFRC'), ('04', 'UofG'), ('20', 'USGS'), ('09', 'Minn.'), ('19', 'USFWS'), ('06', 'Ohio'), ('13', 'OntHydro'), ('99', 'Unkn'), ('11', 'SSFC'), ('26', 'GLLFAS'), ('05', 'UofT'), ('12', 'Priv'), ('98', 'Other'), ('24', 'CORA'), ('07', 'Penn.')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('9', 'Unknown'), ('5', 'Flesh of Back'), ('4', 'Abdominal Insertion'), ('8', 'Anal'), ('1', 'Anterior Dorsal'), ('6', 'Jaw'), ('7', 'Snout'), ('3', 'Posterior Dorsal'), ('2', 'Between Dorsal')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('7', 'Strip Vinyl  '), ('A', 'Internal (Radio)'), ('P', 'PIT tag'), ('5', 'Anchor'), ('3', 'Circular Strap Jaw '), ('4', 'Butt End Jaw '), ('8', 'Secure Tie'), ('2', 'Tubular Vinyl'), ('C', 'Cinch'), ('B', 'Metal Livestock'), ('6', 'Coded Wire'), ('1', 'Streamer')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='date_flag',
            field=models.IntegerField(choices=[(1, 'Reported'), (0, 'Unknown'), (2, 'Derived')], default=1, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='latlon_flag',
            field=models.IntegerField(choices=[(1, 'Reported'), (0, 'Unknown'), (2, 'Derived')], default=1, verbose_name='Spatial Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, choices=[('2', 'Female'), ('1', 'Male'), ('3', 'Hermaphrodite'), ('9', 'Unknown')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='recoveryletter',
            name='method',
            field=models.CharField(choices=[('tfat_template', 'TFAT Template'), ('custom_letter', 'Custom Letter')], default='tfat_template', max_length=30, verbose_name='Generated By'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_flag',
            field=models.IntegerField(choices=[(1, 'Reported'), (0, 'Unknown'), (2, 'Derived')], default=0, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_format',
            field=models.CharField(choices=[('dcr', 'DCR'), ('verbal', 'verbal'), ('letter', 'letter'), ('other', 'other'), ('e-mail', 'e-mail')], default='verbal', max_length=30, verbose_name='Report Format'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('9', 'Unknown'), ('3', 'Hermaphrodite')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('2', 'Yellow'), ('7', 'White'), ('3', 'Red'), ('1', 'Colourless'), ('4', 'Green'), ('9', 'Unknown'), ('5', 'Orange'), ('6', 'Silver')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('26', 'GLLFAS'), ('24', 'CORA'), ('19', 'USFWS'), ('25', 'AOFRC'), ('06', 'Ohio'), ('03', 'Mich.'), ('12', 'Priv'), ('04', 'UofG'), ('08', 'ROM'), ('05', 'UofT'), ('98', 'Other'), ('13', 'OntHydro'), ('10', 'Lakehead'), ('09', 'Minn.'), ('99', 'Unkn'), ('01', 'MNRF'), ('20', 'USGS'), ('02', 'NY'), ('07', 'Penn.'), ('11', 'SSFC')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('5', 'Flesh of Back'), ('2', 'Between Dorsal'), ('6', 'Jaw'), ('8', 'Anal'), ('1', 'Anterior Dorsal'), ('4', 'Abdominal Insertion'), ('3', 'Posterior Dorsal'), ('7', 'Snout'), ('9', 'Unknown')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('6', 'Coded Wire'), ('1', 'Streamer'), ('A', 'Internal (Radio)'), ('P', 'PIT tag'), ('7', 'Strip Vinyl  '), ('B', 'Metal Livestock'), ('5', 'Anchor'), ('4', 'Butt End Jaw '), ('8', 'Secure Tie'), ('3', 'Circular Strap Jaw '), ('2', 'Tubular Vinyl'), ('C', 'Cinch')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('9', 'Unknown'), ('3', 'Hermaphrodite')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='recoveryletter',
            name='method',
            field=models.CharField(choices=[('custom_letter', 'Custom Letter'), ('tfat_template', 'TFAT Template')], default='tfat_template', max_length=30, verbose_name='Generated By'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_format',
            field=models.CharField(choices=[('other', 'other'), ('verbal', 'verbal'), ('dcr', 'DCR'), ('e-mail', 'e-mail'), ('letter', 'letter')], default='verbal', max_length=30, verbose_name='Report Format'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='sex',
            field=models.CharField(blank=True, choices=[('3', 'Hermaphrodite'), ('2', 'Female'), ('9', 'Unknown'), ('1', 'Male')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Species'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('5', 'Orange'), ('3', 'Red'), ('6', 'Silver'), ('7', 'White'), ('9', 'Unknown'), ('2', 'Yellow'), ('1', 'Colourless'), ('4', 'Green')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('98', 'Other'), ('04', 'UofG'), ('01', 'MNRF'), ('08', 'ROM'), ('13', 'OntHydro'), ('99', 'Unkn'), ('20', 'USGS'), ('25', 'AOFRC'), ('19', 'USFWS'), ('05', 'UofT'), ('03', 'Mich.'), ('09', 'Minn.'), ('26', 'GLLFAS'), ('10', 'Lakehead'), ('07', 'Penn.'), ('06', 'Ohio'), ('02', 'NY'), ('12', 'Priv'), ('24', 'CORA'), ('11', 'SSFC')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('1', 'Anterior Dorsal'), ('3', 'Posterior Dorsal'), ('2', 'Between Dorsal'), ('9', 'Unknown'), ('7', 'Snout'), ('8', 'Anal'), ('4', 'Abdominal Insertion'), ('6', 'Jaw'), ('5', 'Flesh of Back')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('5', 'Anchor'), ('C', 'Cinch'), ('3', 'Circular Strap Jaw '), ('6', 'Coded Wire'), ('A', 'Internal (Radio)'), ('4', 'Butt End Jaw '), ('7', 'Strip Vinyl  '), ('8', 'Secure Tie'), ('P', 'PIT tag'), ('B', 'Metal Livestock'), ('2', 'Tubular Vinyl'), ('1', 'Streamer')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='date_flag',
            field=models.IntegerField(choices=[(0, 'Unknown'), (2, 'Derived'), (1, 'Reported')], default=1, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='latlon_flag',
            field=models.IntegerField(choices=[(0, 'Unknown'), (2, 'Derived'), (1, 'Reported')], default=1, verbose_name='Spatial Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, choices=[('3', 'Hermaphrodite'), ('2', 'Female'), ('9', 'Unknown'), ('1', 'Male')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AddField(
            model_name='recovery',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='common.Species'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_flag',
            field=models.IntegerField(choices=[(0, 'Unknown'), (2, 'Derived'), (1, 'Reported')], default=0, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_format',
            field=models.CharField(choices=[('other', 'other'), ('dcr', 'DCR'), ('verbal', 'verbal'), ('e-mail', 'e-mail'), ('letter', 'letter')], default='verbal', max_length=30, verbose_name='Report Format'),
        ),
        migrations.AlterIndexTogether(
            name='encounter',
            index_together={('tagid', 'tagdoc', 'species')},
        ),
        migrations.AlterIndexTogether(
            name='recovery',
            index_together={('tagid', 'tagdoc', 'species')},
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='spc',
        ),
        migrations.RemoveField(
            model_name='recovery',
            name='spc',
        ),
        migrations.AlterField(
            model_name='encounter',
            name='sex',
            field=models.CharField(blank=True, choices=[('3', 'Hermaphrodite'), ('9', 'Unknown'), ('1', 'Male'), ('2', 'Female')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='tagstat',
            field=models.CharField(blank=True, choices=[('A', 'Applied'), ('C', 'Existed on Capture')], db_index=True, default='C', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('3', 'Red'), ('2', 'Yellow'), ('6', 'Silver'), ('9', 'Unknown'), ('1', 'Colourless'), ('5', 'Orange'), ('7', 'White'), ('4', 'Green')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('11', 'SSFC'), ('20', 'USGS'), ('08', 'ROM'), ('24', 'CORA'), ('04', 'UofG'), ('12', 'Priv'), ('99', 'Unkn'), ('03', 'Mich.'), ('07', 'Penn.'), ('19', 'USFWS'), ('09', 'Minn.'), ('05', 'UofT'), ('01', 'MNRF'), ('06', 'Ohio'), ('98', 'Other'), ('10', 'Lakehead'), ('13', 'OntHydro'), ('26', 'GLLFAS'), ('25', 'AOFRC'), ('02', 'NY')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('2', 'Between Dorsal'), ('7', 'Snout'), ('6', 'Jaw'), ('9', 'Unknown'), ('8', 'Anal'), ('1', 'Anterior Dorsal'), ('5', 'Flesh of Back'), ('3', 'Posterior Dorsal'), ('4', 'Abdominal Insertion')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('5', 'Anchor'), ('7', 'Strip Vinyl  '), ('6', 'Coded Wire'), ('3', 'Circular Strap Jaw '), ('4', 'Butt End Jaw '), ('2', 'Tubular Vinyl'), ('B', 'Metal Livestock'), ('8', 'Secure Tie'), ('C', 'Cinch'), ('A', 'Internal (Radio)'), ('1', 'Streamer'), ('P', 'PIT tag')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='date_flag',
            field=models.IntegerField(choices=[(2, 'Derived'), (1, 'Reported'), (0, 'Unknown')], default=1, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='latlon_flag',
            field=models.IntegerField(choices=[(2, 'Derived'), (1, 'Reported'), (0, 'Unknown')], default=1, verbose_name='Spatial Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, choices=[('3', 'Hermaphrodite'), ('9', 'Unknown'), ('1', 'Male'), ('2', 'Female')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_flag',
            field=models.IntegerField(choices=[(2, 'Derived'), (1, 'Reported'), (0, 'Unknown')], default=0, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_format',
            field=models.CharField(choices=[('verbal', 'verbal'), ('letter', 'letter'), ('e-mail', 'e-mail'), ('other', 'other'), ('dcr', 'DCR')], default='verbal', max_length=30, verbose_name='Report Format'),
        ),
        migrations.DeleteModel(
            name='Species',
        ),
        migrations.AlterField(
            model_name='encounter',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('9', 'Unknown'), ('2', 'Female'), ('3', 'Hermaphrodite')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='tagstat',
            field=models.CharField(blank=True, choices=[('C', 'Existed on Capture'), ('A', 'Applied')], db_index=True, default='C', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('3', 'Red'), ('6', 'Silver'), ('2', 'Yellow'), ('9', 'Unknown'), ('4', 'Green'), ('5', 'Orange'), ('7', 'White'), ('1', 'Colourless')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('10', 'Lakehead'), ('20', 'USGS'), ('07', 'Penn.'), ('02', 'NY'), ('98', 'Other'), ('08', 'ROM'), ('11', 'SSFC'), ('25', 'AOFRC'), ('06', 'Ohio'), ('26', 'GLLFAS'), ('03', 'Mich.'), ('09', 'Minn.'), ('12', 'Priv'), ('13', 'OntHydro'), ('01', 'MNRF'), ('24', 'CORA'), ('19', 'USFWS'), ('04', 'UofG'), ('99', 'Unkn'), ('05', 'UofT')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('4', 'Abdominal Insertion'), ('7', 'Snout'), ('8', 'Anal'), ('9', 'Unknown'), ('3', 'Posterior Dorsal'), ('6', 'Jaw'), ('2', 'Between Dorsal'), ('1', 'Anterior Dorsal'), ('5', 'Flesh of Back')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('7', 'Strip Vinyl  '), ('B', 'Metal Livestock'), ('2', 'Tubular Vinyl'), ('5', 'Anchor'), ('C', 'Cinch'), ('P', 'PIT tag'), ('4', 'Butt End Jaw '), ('3', 'Circular Strap Jaw '), ('8', 'Secure Tie'), ('A', 'Internal (Radio)'), ('6', 'Coded Wire'), ('1', 'Streamer')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='date_flag',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Reported'), (2, 'Derived')], default=1, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='latlon_flag',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Reported'), (2, 'Derived')], default=1, verbose_name='Spatial Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('9', 'Unknown'), ('2', 'Female'), ('3', 'Hermaphrodite')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_flag',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Reported'), (2, 'Derived')], default=0, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_format',
            field=models.CharField(choices=[('other', 'other'), ('letter', 'letter'), ('verbal', 'verbal'), ('e-mail', 'e-mail'), ('dcr', 'DCR')], default='verbal', max_length=30, verbose_name='Report Format'),
        ),
        migrations.CreateModel(
            name='TaggedSpecies',
            fields=[
                ('species_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.Species')),
                ('tagged', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['spc_nmco'],
                'verbose_name_plural': 'Tagged Species',
            },
            bases=('common.species',),
            managers=[
                ('all_species', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='encounter',
            name='sex',
            field=models.CharField(blank=True, choices=[('9', 'Unknown'), ('3', 'Hermaphrodite'), ('2', 'Female'), ('1', 'Male')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('1', 'Colourless'), ('3', 'Red'), ('9', 'Unknown'), ('6', 'Silver'), ('4', 'Green'), ('2', 'Yellow'), ('5', 'Orange'), ('7', 'White')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('09', 'Minn.'), ('10', 'Lakehead'), ('98', 'Other'), ('13', 'OntHydro'), ('03', 'Mich.'), ('08', 'ROM'), ('24', 'CORA'), ('99', 'Unkn'), ('19', 'USFWS'), ('25', 'AOFRC'), ('12', 'Priv'), ('05', 'UofT'), ('07', 'Penn.'), ('02', 'NY'), ('04', 'UofG'), ('11', 'SSFC'), ('26', 'GLLFAS'), ('01', 'MNRF'), ('20', 'USGS'), ('06', 'Ohio')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('6', 'Jaw'), ('9', 'Unknown'), ('2', 'Between Dorsal'), ('5', 'Flesh of Back'), ('3', 'Posterior Dorsal'), ('4', 'Abdominal Insertion'), ('7', 'Snout'), ('8', 'Anal'), ('1', 'Anterior Dorsal')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('A', 'Internal (Radio)'), ('B', 'Metal Livestock'), ('6', 'Coded Wire'), ('3', 'Circular Strap Jaw '), ('P', 'PIT tag'), ('1', 'Streamer'), ('5', 'Anchor'), ('C', 'Cinch'), ('2', 'Tubular Vinyl'), ('8', 'Secure Tie'), ('4', 'Butt End Jaw '), ('7', 'Strip Vinyl  ')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='date_flag',
            field=models.IntegerField(choices=[(1, 'Reported'), (2, 'Derived'), (0, 'Unknown')], default=1, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='latlon_flag',
            field=models.IntegerField(choices=[(1, 'Reported'), (2, 'Derived'), (0, 'Unknown')], default=1, verbose_name='Spatial Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, choices=[('9', 'Unknown'), ('3', 'Hermaphrodite'), ('2', 'Female'), ('1', 'Male')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='recoveryletter',
            name='method',
            field=models.CharField(choices=[('tfat_template', 'TFAT Template'), ('custom_letter', 'Custom Letter')], default='tfat_template', max_length=30, verbose_name='Generated By'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_flag',
            field=models.IntegerField(choices=[(1, 'Reported'), (2, 'Derived'), (0, 'Unknown')], default=0, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_format',
            field=models.CharField(choices=[('e-mail', 'e-mail'), ('verbal', 'verbal'), ('letter', 'letter'), ('other', 'other'), ('dcr', 'DCR')], default='verbal', max_length=30, verbose_name='Report Format'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='sex',
            field=models.CharField(blank=True, choices=[('9', 'Unknown'), ('3', 'Hermaphrodite'), ('1', 'Male'), ('2', 'Female')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfat.TaggedSpecies'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('3', 'Red'), ('6', 'Silver'), ('9', 'Unknown'), ('2', 'Yellow'), ('7', 'White'), ('1', 'Colourless'), ('4', 'Green'), ('5', 'Orange')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('12', 'Priv'), ('09', 'Minn.'), ('06', 'Ohio'), ('13', 'OntHydro'), ('24', 'CORA'), ('11', 'SSFC'), ('04', 'UofG'), ('08', 'ROM'), ('05', 'UofT'), ('99', 'Unkn'), ('20', 'USGS'), ('10', 'Lakehead'), ('07', 'Penn.'), ('01', 'MNRF'), ('02', 'NY'), ('26', 'GLLFAS'), ('98', 'Other'), ('19', 'USFWS'), ('25', 'AOFRC'), ('03', 'Mich.')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('8', 'Anal'), ('9', 'Unknown'), ('7', 'Snout'), ('2', 'Between Dorsal'), ('5', 'Flesh of Back'), ('4', 'Abdominal Insertion'), ('6', 'Jaw'), ('1', 'Anterior Dorsal'), ('3', 'Posterior Dorsal')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('3', 'Circular Strap Jaw '), ('P', 'PIT tag'), ('A', 'Internal (Radio)'), ('C', 'Cinch'), ('1', 'Streamer'), ('7', 'Strip Vinyl  '), ('8', 'Secure Tie'), ('4', 'Butt End Jaw '), ('2', 'Tubular Vinyl'), ('6', 'Coded Wire'), ('B', 'Metal Livestock'), ('5', 'Anchor')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, choices=[('9', 'Unknown'), ('3', 'Hermaphrodite'), ('1', 'Male'), ('2', 'Female')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='tfat.TaggedSpecies'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_format',
            field=models.CharField(choices=[('letter', 'letter'), ('verbal', 'verbal'), ('other', 'other'), ('e-mail', 'e-mail'), ('dcr', 'DCR')], default='verbal', max_length=30, verbose_name='Report Format'),
        ),
        migrations.AlterModelOptions(
            name='joepublic',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name_plural': 'Tag Reporters'},
        ),
        migrations.AlterModelManagers(
            name='taggedspecies',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='encounter',
            name='sex',
            field=models.CharField(blank=True, choices=[('3', 'Hermaphrodite'), ('2', 'Female'), ('1', 'Male'), ('9', 'Unknown')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('7', 'White'), ('6', 'Silver'), ('1', 'Colourless'), ('4', 'Green'), ('3', 'Red'), ('9', 'Unknown'), ('2', 'Yellow'), ('5', 'Orange')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('26', 'GLLFAS'), ('03', 'Mich.'), ('99', 'Unkn'), ('13', 'OntHydro'), ('20', 'USGS'), ('98', 'Other'), ('02', 'NY'), ('04', 'UofG'), ('19', 'USFWS'), ('25', 'AOFRC'), ('05', 'UofT'), ('24', 'CORA'), ('09', 'Minn.'), ('10', 'Lakehead'), ('08', 'ROM'), ('11', 'SSFC'), ('07', 'Penn.'), ('06', 'Ohio'), ('01', 'MNRF'), ('12', 'Priv')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('6', 'Jaw'), ('5', 'Flesh of Back'), ('2', 'Between Dorsal'), ('8', 'Anal'), ('4', 'Abdominal Insertion'), ('1', 'Anterior Dorsal'), ('9', 'Unknown'), ('3', 'Posterior Dorsal'), ('7', 'Snout')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('8', 'Secure Tie'), ('5', 'Anchor'), ('6', 'Coded Wire'), ('A', 'Internal (Radio)'), ('B', 'Metal Livestock'), ('C', 'Cinch'), ('P', 'PIT tag'), ('2', 'Tubular Vinyl'), ('4', 'Butt End Jaw '), ('3', 'Circular Strap Jaw '), ('1', 'Streamer'), ('7', 'Strip Vinyl  ')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='date_flag',
            field=models.IntegerField(choices=[(1, 'Reported'), (0, 'Unknown'), (2, 'Derived')], default=1, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='latlon_flag',
            field=models.IntegerField(choices=[(1, 'Reported'), (0, 'Unknown'), (2, 'Derived')], default=1, verbose_name='Spatial Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, choices=[('3', 'Hermaphrodite'), ('2', 'Female'), ('1', 'Male'), ('9', 'Unknown')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='report',
            name='associated_file',
            field=models.FileField(blank=True, null=True, upload_to='tfat_tag_reports'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_flag',
            field=models.IntegerField(choices=[(1, 'Reported'), (0, 'Unknown'), (2, 'Derived')], default=0, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_format',
            field=models.CharField(choices=[('e-mail', 'e-mail'), ('other', 'other'), ('letter', 'letter'), ('dcr', 'DCR'), ('verbal', 'verbal')], default='verbal', max_length=30, verbose_name='Report Format'),
        ),
    ]
