# Generated by Django 2.2.10 on 2020-02-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfollowup',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='sex',
            field=models.CharField(blank=True, choices=[('2', 'Female'), ('3', 'Hermaphrodite'), ('9', 'Unknown'), ('1', 'Male')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='tagstat',
            field=models.CharField(blank=True, choices=[('C', 'Existed on Capture'), ('A', 'Applied')], db_index=True, default='C', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('2', 'Yellow'), ('7', 'White'), ('9', 'Unknown'), ('3', 'Red'), ('4', 'Green'), ('6', 'Silver'), ('1', 'Colourless'), ('5', 'Orange')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('01', 'Ontario Ministry of Natural Resources'), ('99', 'Unknown'), ('20', 'USGS'), ('03', 'State of Michigan'), ('11', 'Sir Sandford Fleming College'), ('19', 'USFWS'), ('12', 'Private Club'), ('09', 'State of Minnesota'), ('98', 'Other'), ('06', 'State of Ohio'), ('05', 'University of Toronto'), ('26', 'GLLFAS'), ('08', 'Royal Ontario Museum'), ('02', 'New York State'), ('25', 'AOFRC'), ('10', 'Lakehead University'), ('07', 'State of Pennsylvania'), ('04', 'University of Guelph'), ('24', 'CORA'), ('13', 'Ontario Hydro')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('2', 'Between Dorsal'), ('9', 'Unknown'), ('1', 'Anterior Dorsal'), ('6', 'Jaw'), ('3', 'Posterior Dorsal'), ('5', 'Flesh of Back'), ('7', 'Snout'), ('4', 'Abdominal Insertion'), ('8', 'Anal')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('2', 'Tubular Vinyl'), ('C', 'Cinch'), ('8', 'Secure Tie'), ('3', 'Circular Strap Jaw '), ('B', 'Metal Livestock'), ('P', 'PIT tag'), ('1', 'Streamer'), ('5', 'Anchor'), ('7', 'Strip Vinyl  '), ('4', 'Butt End Jaw '), ('A', 'Internal (Radio)'), ('6', 'Coded Wire')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='date_flag',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Reported'), (2, 'Derived')], default=1, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='latlon_flag',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Reported'), (2, 'Derived')], default=1, verbose_name='Spatial Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, choices=[('2', 'Female'), ('3', 'Hermaphrodite'), ('9', 'Unknown'), ('1', 'Male')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_flag',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Reported'), (2, 'Derived')], default=0, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_format',
            field=models.CharField(choices=[('verbal', 'verbal'), ('letter', 'letter'), ('e-mail', 'e-mail'), ('dcr', 'DCR'), ('other', 'other')], default='verbal', max_length=30, verbose_name='Report Format'),
        ),
        migrations.AlterUniqueTogether(
            name='reportfollowup',
            unique_together={('id', 'status')},
        ),
    ]
