# Generated by Django 2.2.10 on 2020-06-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfat', '0001_initial_squashed_0015_upload_to_tfat_tag_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='sex',
            field=models.CharField(blank=True, choices=[('9', 'Unknown'), ('1', 'Male'), ('3', 'Hermaphrodite'), ('2', 'Female')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='tagstat',
            field=models.CharField(blank=True, choices=[('A', 'Applied'), ('C', 'Existed on Capture')], db_index=True, default='C', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('5', 'Orange'), ('7', 'White'), ('6', 'Silver'), ('9', 'Unknown'), ('4', 'Green'), ('3', 'Red'), ('2', 'Yellow'), ('1', 'Colourless')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('04', 'UofG'), ('05', 'UofT'), ('01', 'MNRF'), ('11', 'SSFC'), ('25', 'AOFRC'), ('06', 'Ohio'), ('10', 'Lakehead'), ('07', 'Penn.'), ('20', 'USGS'), ('13', 'OntHydro'), ('26', 'GLLFAS'), ('08', 'ROM'), ('19', 'USFWS'), ('24', 'CORA'), ('98', 'Other'), ('02', 'NY'), ('09', 'Minn.'), ('99', 'Unkn'), ('12', 'Priv'), ('03', 'Mich.')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('8', 'Anal'), ('7', 'Snout'), ('4', 'Abdominal Insertion'), ('6', 'Jaw'), ('3', 'Posterior Dorsal'), ('9', 'Unknown'), ('2', 'Between Dorsal'), ('5', 'Flesh of Back'), ('1', 'Anterior Dorsal')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('5', 'Anchor'), ('A', 'Internal (Radio)'), ('B', 'Metal Livestock'), ('C', 'Cinch'), ('P', 'PIT tag'), ('3', 'Circular Strap Jaw '), ('7', 'Strip Vinyl  '), ('8', 'Secure Tie'), ('2', 'Tubular Vinyl'), ('1', 'Streamer'), ('6', 'Coded Wire'), ('4', 'Butt End Jaw ')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='date_flag',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Reported'), (2, 'Derived')], default=1, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='latlon_flag',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Reported'), (2, 'Derived')], default=1, verbose_name='Spatial Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, choices=[('9', 'Unknown'), ('1', 'Male'), ('3', 'Hermaphrodite'), ('2', 'Female')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='report',
            name='associated_file',
            field=models.FileField(blank=True, null=True, upload_to='tfat_tag_reports/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_flag',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Reported'), (2, 'Derived')], default=0, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_format',
            field=models.CharField(choices=[('letter', 'letter'), ('e-mail', 'e-mail'), ('dcr', 'DCR'), ('other', 'other'), ('verbal', 'verbal')], default='verbal', max_length=30, verbose_name='Report Format'),
        ),
    ]
