# Generated by Django 3.2.12 on 2022-04-01 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tfat', '0002_add_id_autofield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Hermaphrodite'), ('9', 'Unknown')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='project',
            name='dbase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tfat.database'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('1', 'Colourless'), ('2', 'Yellow'), ('3', 'Red'), ('4', 'Green'), ('5', 'Orange'), ('6', 'Silver'), ('7', 'White'), ('9', 'Unknown')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('01', 'MNRF'), ('02', 'NY'), ('03', 'Mich.'), ('04', 'UofG'), ('05', 'UofT'), ('06', 'Ohio'), ('07', 'Penn.'), ('08', 'ROM'), ('09', 'Minn.'), ('10', 'Lakehead'), ('11', 'SSFC'), ('12', 'Priv'), ('13', 'OntHydro'), ('19', 'USFWS'), ('20', 'USGS'), ('24', 'CORA'), ('25', 'AOFRC'), ('26', 'GLLFAS'), ('98', 'Other'), ('99', 'Unkn')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('1', 'Anterior Dorsal'), ('2', 'Between Dorsal'), ('3', 'Posterior Dorsal'), ('4', 'Abdominal Insertion'), ('5', 'Flesh of Back'), ('6', 'Jaw'), ('7', 'Snout'), ('8', 'Anal'), ('9', 'Unknown')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('1', 'Streamer'), ('2', 'Tubular Vinyl'), ('3', 'Circular Strap Jaw '), ('4', 'Butt End Jaw '), ('5', 'Anchor'), ('6', 'Coded Wire'), ('7', 'Strip Vinyl  '), ('8', 'Secure Tie'), ('A', 'Internal (Radio)'), ('B', 'Metal Livestock'), ('C', 'Cinch'), ('P', 'PIT tag')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='date_flag',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Reported'), (2, 'Derived')], default=1, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='latlon_flag',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Reported'), (2, 'Derived')], default=1, verbose_name='Spatial Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Hermaphrodite'), ('9', 'Unknown')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='report',
            name='associated_file',
            field=models.FileField(blank=True, null=True, upload_to='tfat_tag_reports/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_flag',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Reported'), (2, 'Derived')], default=0, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_format',
            field=models.CharField(choices=[('verbal', 'verbal'), ('e-mail', 'e-mail'), ('letter', 'letter'), ('dcr', 'DCR'), ('other', 'other')], default='verbal', max_length=30, verbose_name='Report Format'),
        ),
        migrations.AddConstraint(
            model_name='reportfollowup',
            constraint=models.UniqueConstraint(fields=('report', 'status'), name='unique report_status'),
        ),
    ]
