# Generated by Django 2.2.10 on 2020-02-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfat', '0002_auto_20200220_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportfollowup',
            old_name='create_by',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='encounter',
            name='sex',
            field=models.CharField(blank=True, choices=[('3', 'Hermaphrodite'), ('1', 'Male'), ('9', 'Unknown'), ('2', 'Female')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='tagstat',
            field=models.CharField(blank=True, choices=[('A', 'Applied'), ('C', 'Existed on Capture')], db_index=True, default='C', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('1', 'Colourless'), ('2', 'Yellow'), ('5', 'Orange'), ('7', 'White'), ('9', 'Unknown'), ('4', 'Green'), ('3', 'Red'), ('6', 'Silver')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('19', 'USFWS'), ('01', 'Ontario Ministry of Natural Resources'), ('25', 'AOFRC'), ('07', 'State of Pennsylvania'), ('06', 'State of Ohio'), ('20', 'USGS'), ('98', 'Other'), ('04', 'University of Guelph'), ('26', 'GLLFAS'), ('09', 'State of Minnesota'), ('05', 'University of Toronto'), ('10', 'Lakehead University'), ('24', 'CORA'), ('99', 'Unknown'), ('12', 'Private Club'), ('08', 'Royal Ontario Museum'), ('02', 'New York State'), ('11', 'Sir Sandford Fleming College'), ('03', 'State of Michigan'), ('13', 'Ontario Hydro')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('6', 'Jaw'), ('5', 'Flesh of Back'), ('1', 'Anterior Dorsal'), ('8', 'Anal'), ('9', 'Unknown'), ('4', 'Abdominal Insertion'), ('7', 'Snout'), ('3', 'Posterior Dorsal'), ('2', 'Between Dorsal')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('3', 'Circular Strap Jaw '), ('P', 'PIT tag'), ('4', 'Butt End Jaw '), ('B', 'Metal Livestock'), ('C', 'Cinch'), ('6', 'Coded Wire'), ('A', 'Internal (Radio)'), ('1', 'Streamer'), ('8', 'Secure Tie'), ('5', 'Anchor'), ('7', 'Strip Vinyl  '), ('2', 'Tubular Vinyl')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='date_flag',
            field=models.IntegerField(choices=[(1, 'Reported'), (0, 'Unknown'), (2, 'Derived')], default=1, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='latlon_flag',
            field=models.IntegerField(choices=[(1, 'Reported'), (0, 'Unknown'), (2, 'Derived')], default=1, verbose_name='Spatial Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, choices=[('3', 'Hermaphrodite'), ('1', 'Male'), ('9', 'Unknown'), ('2', 'Female')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_flag',
            field=models.IntegerField(choices=[(1, 'Reported'), (0, 'Unknown'), (2, 'Derived')], default=0, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_format',
            field=models.CharField(choices=[('dcr', 'DCR'), ('verbal', 'verbal'), ('e-mail', 'e-mail'), ('letter', 'letter'), ('other', 'other')], default='verbal', max_length=30, verbose_name='Report Format'),
        ),
        migrations.AlterField(
            model_name='reportfollowup',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Not Requested'), (10, 'Requested'), (20, 'Intialized'), (30, 'Completed')], db_index=True, default=0, verbose_name='Follow Up Status'),
        ),
    ]
