# Generated by Django 2.2.10 on 2020-02-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfat', '0003_auto_20200220_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Hermaphrodite'), ('9', 'Unknown')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('1', 'Colourless'), ('6', 'Silver'), ('9', 'Unknown'), ('5', 'Orange'), ('4', 'Green'), ('2', 'Yellow'), ('7', 'White'), ('3', 'Red')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('11', 'Sir Sandford Fleming College'), ('01', 'Ontario Ministry of Natural Resources'), ('09', 'State of Minnesota'), ('10', 'Lakehead University'), ('12', 'Private Club'), ('04', 'University of Guelph'), ('25', 'AOFRC'), ('26', 'GLLFAS'), ('03', 'State of Michigan'), ('06', 'State of Ohio'), ('99', 'Unknown'), ('20', 'USGS'), ('05', 'University of Toronto'), ('24', 'CORA'), ('07', 'State of Pennsylvania'), ('02', 'New York State'), ('98', 'Other'), ('13', 'Ontario Hydro'), ('08', 'Royal Ontario Museum'), ('19', 'USFWS')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('9', 'Unknown'), ('2', 'Between Dorsal'), ('8', 'Anal'), ('5', 'Flesh of Back'), ('7', 'Snout'), ('4', 'Abdominal Insertion'), ('1', 'Anterior Dorsal'), ('3', 'Posterior Dorsal'), ('6', 'Jaw')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('5', 'Anchor'), ('C', 'Cinch'), ('4', 'Butt End Jaw '), ('3', 'Circular Strap Jaw '), ('A', 'Internal (Radio)'), ('7', 'Strip Vinyl  '), ('6', 'Coded Wire'), ('8', 'Secure Tie'), ('P', 'PIT tag'), ('B', 'Metal Livestock'), ('2', 'Tubular Vinyl'), ('1', 'Streamer')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Hermaphrodite'), ('9', 'Unknown')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_format',
            field=models.CharField(choices=[('other', 'other'), ('letter', 'letter'), ('verbal', 'verbal'), ('dcr', 'DCR'), ('e-mail', 'e-mail')], default='verbal', max_length=30, verbose_name='Report Format'),
        ),
        migrations.AlterField(
            model_name='reportfollowup',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('intialized', 'Intialized'), ('completed', 'Completed')], db_index=True, default='requested', max_length=12, verbose_name='Follow Up Status'),
        ),
    ]
