# Generated by Django 2.2.17 on 2021-06-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfat', '0003_auto_20210108_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='sex',
            field=models.CharField(blank=True, choices=[('9', 'Unknown'), ('2', 'Female'), ('1', 'Male'), ('3', 'Hermaphrodite')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('5', 'Orange'), ('4', 'Green'), ('2', 'Yellow'), ('6', 'Silver'), ('9', 'Unknown'), ('3', 'Red'), ('1', 'Colourless'), ('7', 'White')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('25', 'AOFRC'), ('08', 'ROM'), ('99', 'Unkn'), ('04', 'UofG'), ('11', 'SSFC'), ('13', 'OntHydro'), ('07', 'Penn.'), ('06', 'Ohio'), ('26', 'GLLFAS'), ('05', 'UofT'), ('02', 'NY'), ('12', 'Priv'), ('09', 'Minn.'), ('98', 'Other'), ('24', 'CORA'), ('19', 'USFWS'), ('03', 'Mich.'), ('01', 'MNRF'), ('20', 'USGS'), ('10', 'Lakehead')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('3', 'Posterior Dorsal'), ('5', 'Flesh of Back'), ('7', 'Snout'), ('1', 'Anterior Dorsal'), ('6', 'Jaw'), ('8', 'Anal'), ('9', 'Unknown'), ('4', 'Abdominal Insertion'), ('2', 'Between Dorsal')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('6', 'Coded Wire'), ('P', 'PIT tag'), ('A', 'Internal (Radio)'), ('3', 'Circular Strap Jaw '), ('5', 'Anchor'), ('1', 'Streamer'), ('2', 'Tubular Vinyl'), ('4', 'Butt End Jaw '), ('7', 'Strip Vinyl  '), ('8', 'Secure Tie'), ('C', 'Cinch'), ('B', 'Metal Livestock')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='date_flag',
            field=models.IntegerField(choices=[(2, 'Derived'), (1, 'Reported'), (0, 'Unknown')], default=1, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='latlon_flag',
            field=models.IntegerField(choices=[(2, 'Derived'), (1, 'Reported'), (0, 'Unknown')], default=1, verbose_name='Spatial Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, choices=[('9', 'Unknown'), ('2', 'Female'), ('1', 'Male'), ('3', 'Hermaphrodite')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_flag',
            field=models.IntegerField(choices=[(2, 'Derived'), (1, 'Reported'), (0, 'Unknown')], default=0, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_format',
            field=models.CharField(choices=[('verbal', 'verbal'), ('e-mail', 'e-mail'), ('letter', 'letter'), ('dcr', 'DCR'), ('other', 'other')], default='verbal', max_length=30, verbose_name='Report Format'),
        ),
##        migrations.AddConstraint(
##            model_name='reportfollowup',
##            constraint=models.UniqueConstraint(fields=('report', 'status'), name='unique report_status'),
##        ),
    ]
