# Generated by Django 2.2.10 on 2020-02-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfat', '0004_auto_20200220_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('1', 'Colourless'), ('4', 'Green'), ('9', 'Unknown'), ('3', 'Red'), ('7', 'White'), ('2', 'Yellow'), ('5', 'Orange'), ('6', 'Silver')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('12', 'Private Club'), ('05', 'University of Toronto'), ('10', 'Lakehead University'), ('25', 'AOFRC'), ('99', 'Unknown'), ('08', 'Royal Ontario Museum'), ('24', 'CORA'), ('09', 'State of Minnesota'), ('02', 'New York State'), ('11', 'Sir Sandford Fleming College'), ('03', 'State of Michigan'), ('07', 'State of Pennsylvania'), ('01', 'Ontario Ministry of Natural Resources'), ('19', 'USFWS'), ('26', 'GLLFAS'), ('04', 'University of Guelph'), ('13', 'Ontario Hydro'), ('20', 'USGS'), ('06', 'State of Ohio'), ('98', 'Other')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('2', 'Between Dorsal'), ('7', 'Snout'), ('9', 'Unknown'), ('3', 'Posterior Dorsal'), ('1', 'Anterior Dorsal'), ('8', 'Anal'), ('4', 'Abdominal Insertion'), ('6', 'Jaw'), ('5', 'Flesh of Back')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('P', 'PIT tag'), ('4', 'Butt End Jaw '), ('1', 'Streamer'), ('5', 'Anchor'), ('B', 'Metal Livestock'), ('C', 'Cinch'), ('7', 'Strip Vinyl  '), ('3', 'Circular Strap Jaw '), ('6', 'Coded Wire'), ('A', 'Internal (Radio)'), ('2', 'Tubular Vinyl'), ('8', 'Secure Tie')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='date_flag',
            field=models.IntegerField(choices=[(2, 'Derived'), (1, 'Reported'), (0, 'Unknown')], default=1, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='latlon_flag',
            field=models.IntegerField(choices=[(2, 'Derived'), (1, 'Reported'), (0, 'Unknown')], default=1, verbose_name='Spatial Flag'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_flag',
            field=models.IntegerField(choices=[(2, 'Derived'), (1, 'Reported'), (0, 'Unknown')], default=0, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_format',
            field=models.CharField(choices=[('letter', 'letter'), ('other', 'other'), ('dcr', 'DCR'), ('verbal', 'verbal'), ('e-mail', 'e-mail')], default='verbal', max_length=30, verbose_name='Report Format'),
        ),
        migrations.AlterField(
            model_name='reportfollowup',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('initialized', 'Initialized'), ('completed', 'Completed')], db_index=True, default='requested', max_length=12, verbose_name='Follow Up Status'),
        ),
        migrations.AddConstraint(
            model_name='reportfollowup',
            constraint=models.UniqueConstraint(fields=('id', 'status'), name='unique status'),
        ),
    ]
