# Generated by Django 2.2.17 on 2021-06-17 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tfat', '0004_auto_20210616_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Hermaphrodite'), ('9', 'Unknown')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='tagstat',
            field=models.CharField(blank=True, choices=[('A', 'Applied'), ('C', 'Existed on Capture')], db_index=True, default='C', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='dbase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tfat.Database'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('9', 'Unknown'), ('3', 'Red'), ('5', 'Orange'), ('7', 'White'), ('6', 'Silver'), ('1', 'Colourless'), ('4', 'Green'), ('2', 'Yellow')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('20', 'USGS'), ('12', 'Priv'), ('03', 'Mich.'), ('08', 'ROM'), ('25', 'AOFRC'), ('07', 'Penn.'), ('02', 'NY'), ('04', 'UofG'), ('99', 'Unkn'), ('98', 'Other'), ('13', 'OntHydro'), ('06', 'Ohio'), ('11', 'SSFC'), ('26', 'GLLFAS'), ('24', 'CORA'), ('01', 'MNRF'), ('19', 'USFWS'), ('05', 'UofT'), ('10', 'Lakehead'), ('09', 'Minn.')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('9', 'Unknown'), ('1', 'Anterior Dorsal'), ('3', 'Posterior Dorsal'), ('7', 'Snout'), ('2', 'Between Dorsal'), ('6', 'Jaw'), ('5', 'Flesh of Back'), ('4', 'Abdominal Insertion'), ('8', 'Anal')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('4', 'Butt End Jaw '), ('8', 'Secure Tie'), ('3', 'Circular Strap Jaw '), ('7', 'Strip Vinyl  '), ('B', 'Metal Livestock'), ('2', 'Tubular Vinyl'), ('5', 'Anchor'), ('A', 'Internal (Radio)'), ('1', 'Streamer'), ('6', 'Coded Wire'), ('C', 'Cinch'), ('P', 'PIT tag')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='date_flag',
            field=models.IntegerField(choices=[(1, 'Reported'), (0, 'Unknown'), (2, 'Derived')], default=1, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='latlon_flag',
            field=models.IntegerField(choices=[(1, 'Reported'), (0, 'Unknown'), (2, 'Derived')], default=1, verbose_name='Spatial Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Hermaphrodite'), ('9', 'Unknown')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='recoveryletter',
            name='method',
            field=models.CharField(choices=[('custom_letter', 'Custom Letter'), ('tfat_template', 'TFAT Template')], default='tfat_template', max_length=30, verbose_name='Generated By'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_flag',
            field=models.IntegerField(choices=[(1, 'Reported'), (0, 'Unknown'), (2, 'Derived')], default=0, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_format',
            field=models.CharField(choices=[('dcr', 'DCR'), ('other', 'other'), ('verbal', 'verbal'), ('letter', 'letter'), ('e-mail', 'e-mail')], default='verbal', max_length=30, verbose_name='Report Format'),
        ),
##        migrations.AddConstraint(
##            model_name='reportfollowup',
##            constraint=models.UniqueConstraint(fields=('report', 'status'), name='unique report_status'),
##        ),
    ]
