# Generated by Django 2.2.10 on 2020-02-21 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tfat', '0005_auto_20200220_1718'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reportfollowup',
            name='unique status',
        ),
        migrations.AlterField(
            model_name='encounter',
            name='sex',
            field=models.CharField(blank=True, choices=[('2', 'Female'), ('1', 'Male'), ('9', 'Unknown'), ('3', 'Hermaphrodite')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('9', 'Unknown'), ('3', 'Red'), ('5', 'Orange'), ('7', 'White'), ('4', 'Green'), ('1', 'Colourless'), ('6', 'Silver'), ('2', 'Yellow')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('20', 'USGS'), ('04', 'University of Guelph'), ('06', 'State of Ohio'), ('12', 'Private Club'), ('10', 'Lakehead University'), ('05', 'University of Toronto'), ('19', 'USFWS'), ('11', 'Sir Sandford Fleming College'), ('02', 'New York State'), ('25', 'AOFRC'), ('09', 'State of Minnesota'), ('24', 'CORA'), ('08', 'Royal Ontario Museum'), ('01', 'Ontario Ministry of Natural Resources'), ('03', 'State of Michigan'), ('26', 'GLLFAS'), ('13', 'Ontario Hydro'), ('99', 'Unknown'), ('07', 'State of Pennsylvania'), ('98', 'Other')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('1', 'Anterior Dorsal'), ('8', 'Anal'), ('3', 'Posterior Dorsal'), ('9', 'Unknown'), ('4', 'Abdominal Insertion'), ('6', 'Jaw'), ('7', 'Snout'), ('2', 'Between Dorsal'), ('5', 'Flesh of Back')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('C', 'Cinch'), ('7', 'Strip Vinyl  '), ('8', 'Secure Tie'), ('5', 'Anchor'), ('4', 'Butt End Jaw '), ('A', 'Internal (Radio)'), ('6', 'Coded Wire'), ('B', 'Metal Livestock'), ('1', 'Streamer'), ('2', 'Tubular Vinyl'), ('P', 'PIT tag'), ('3', 'Circular Strap Jaw ')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='date_flag',
            field=models.IntegerField(choices=[(1, 'Reported'), (2, 'Derived'), (0, 'Unknown')], default=1, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='latlon_flag',
            field=models.IntegerField(choices=[(1, 'Reported'), (2, 'Derived'), (0, 'Unknown')], default=1, verbose_name='Spatial Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='tfat.Report'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, choices=[('2', 'Female'), ('1', 'Male'), ('9', 'Unknown'), ('3', 'Hermaphrodite')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_flag',
            field=models.IntegerField(choices=[(1, 'Reported'), (2, 'Derived'), (0, 'Unknown')], default=0, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_format',
            field=models.CharField(choices=[('e-mail', 'e-mail'), ('other', 'other'), ('dcr', 'DCR'), ('verbal', 'verbal'), ('letter', 'letter')], default='verbal', max_length=30, verbose_name='Report Format'),
        ),
        migrations.AlterUniqueTogether(
            name='reportfollowup',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='reportfollowup',
            constraint=models.UniqueConstraint(fields=('report', 'status'), name='unique report_status'),
        ),
    ]
