# Generated by Django 2.2.10 on 2020-02-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfat', '0006_auto_20200221_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='follow_up_status',
            field=models.CharField(blank=True, choices=[('requested', 'Requested'), ('initialized', 'Initialized'), ('completed', 'Completed')], db_index=True, default=None, max_length=12, null=True, verbose_name='Follow Up Status'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='sex',
            field=models.CharField(blank=True, choices=[('3', 'Hermaphrodite'), ('2', 'Female'), ('1', 'Male'), ('9', 'Unknown')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('7', 'White'), ('6', 'Silver'), ('5', 'Orange'), ('9', 'Unknown'), ('3', 'Red'), ('4', 'Green'), ('2', 'Yellow'), ('1', 'Colourless')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('09', 'State of Minnesota'), ('07', 'State of Pennsylvania'), ('12', 'Private Club'), ('01', 'Ontario Ministry of Natural Resources'), ('19', 'USFWS'), ('98', 'Other'), ('08', 'Royal Ontario Museum'), ('11', 'Sir Sandford Fleming College'), ('25', 'AOFRC'), ('02', 'New York State'), ('20', 'USGS'), ('03', 'State of Michigan'), ('06', 'State of Ohio'), ('26', 'GLLFAS'), ('99', 'Unknown'), ('24', 'CORA'), ('13', 'Ontario Hydro'), ('04', 'University of Guelph'), ('10', 'Lakehead University'), ('05', 'University of Toronto')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('6', 'Jaw'), ('9', 'Unknown'), ('2', 'Between Dorsal'), ('8', 'Anal'), ('5', 'Flesh of Back'), ('4', 'Abdominal Insertion'), ('3', 'Posterior Dorsal'), ('7', 'Snout'), ('1', 'Anterior Dorsal')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('3', 'Circular Strap Jaw '), ('7', 'Strip Vinyl  '), ('P', 'PIT tag'), ('5', 'Anchor'), ('4', 'Butt End Jaw '), ('1', 'Streamer'), ('A', 'Internal (Radio)'), ('B', 'Metal Livestock'), ('2', 'Tubular Vinyl'), ('C', 'Cinch'), ('8', 'Secure Tie'), ('6', 'Coded Wire')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='date_flag',
            field=models.IntegerField(choices=[(0, 'Unknown'), (2, 'Derived'), (1, 'Reported')], default=1, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='latlon_flag',
            field=models.IntegerField(choices=[(0, 'Unknown'), (2, 'Derived'), (1, 'Reported')], default=1, verbose_name='Spatial Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, choices=[('3', 'Hermaphrodite'), ('2', 'Female'), ('1', 'Male'), ('9', 'Unknown')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_flag',
            field=models.IntegerField(choices=[(0, 'Unknown'), (2, 'Derived'), (1, 'Reported')], default=0, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_format',
            field=models.CharField(choices=[('letter', 'letter'), ('verbal', 'verbal'), ('e-mail', 'e-mail'), ('other', 'other'), ('dcr', 'DCR')], default='verbal', max_length=30, verbose_name='Report Format'),
        ),
    ]
