# Generated by Django 2.2.10 on 2020-04-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfat', '0007_auto_20200224_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-report_date']},
        ),
        migrations.AlterField(
            model_name='encounter',
            name='sex',
            field=models.CharField(blank=True, choices=[('2', 'Female'), ('1', 'Male'), ('3', 'Hermaphrodite'), ('9', 'Unknown')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='tagstat',
            field=models.CharField(blank=True, choices=[('C', 'Existed on Capture'), ('A', 'Applied')], db_index=True, default='C', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('9', 'Unknown'), ('5', 'Orange'), ('2', 'Yellow'), ('3', 'Red'), ('7', 'White'), ('1', 'Colourless'), ('4', 'Green'), ('6', 'Silver')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('01', 'MNRF'), ('08', 'ROM'), ('10', 'Lakehead'), ('02', 'NY'), ('03', 'Mich.'), ('25', 'AOFRC'), ('04', 'UofG'), ('20', 'USGS'), ('09', 'Minn.'), ('19', 'USFWS'), ('06', 'Ohio'), ('13', 'OntHydro'), ('99', 'Unkn'), ('11', 'SSFC'), ('26', 'GLLFAS'), ('05', 'UofT'), ('12', 'Priv'), ('98', 'Other'), ('24', 'CORA'), ('07', 'Penn.')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('9', 'Unknown'), ('5', 'Flesh of Back'), ('4', 'Abdominal Insertion'), ('8', 'Anal'), ('1', 'Anterior Dorsal'), ('6', 'Jaw'), ('7', 'Snout'), ('3', 'Posterior Dorsal'), ('2', 'Between Dorsal')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('7', 'Strip Vinyl  '), ('A', 'Internal (Radio)'), ('P', 'PIT tag'), ('5', 'Anchor'), ('3', 'Circular Strap Jaw '), ('4', 'Butt End Jaw '), ('8', 'Secure Tie'), ('2', 'Tubular Vinyl'), ('C', 'Cinch'), ('B', 'Metal Livestock'), ('6', 'Coded Wire'), ('1', 'Streamer')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='date_flag',
            field=models.IntegerField(choices=[(1, 'Reported'), (0, 'Unknown'), (2, 'Derived')], default=1, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='latlon_flag',
            field=models.IntegerField(choices=[(1, 'Reported'), (0, 'Unknown'), (2, 'Derived')], default=1, verbose_name='Spatial Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, choices=[('2', 'Female'), ('1', 'Male'), ('3', 'Hermaphrodite'), ('9', 'Unknown')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='recoveryletter',
            name='method',
            field=models.CharField(choices=[('tfat_template', 'TFAT Template'), ('custom_letter', 'Custom Letter')], default='tfat_template', max_length=30, verbose_name='Generated By'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_flag',
            field=models.IntegerField(choices=[(1, 'Reported'), (0, 'Unknown'), (2, 'Derived')], default=0, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_format',
            field=models.CharField(choices=[('dcr', 'DCR'), ('verbal', 'verbal'), ('letter', 'letter'), ('other', 'other'), ('e-mail', 'e-mail')], default='verbal', max_length=30, verbose_name='Report Format'),
        ),
    ]
