# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfat', '0007_auto_20180918_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='sex',
            field=models.CharField(blank=True, null=True, choices=[('9', 'Unknown'), ('3', 'Hermaphrodite'), ('2', 'Female'), ('1', 'Male')], max_length=3, verbose_name='Sex', default='9'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='tagstat',
            field=models.CharField(null=True, choices=[('C', 'Existed on Capture'), ('A', 'Applied')], max_length=4, blank=True, default='C', db_index=True),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('1', 'Colourless'), ('6', 'Silver'), ('3', 'Red'), ('7', 'White'), ('5', 'Orange'), ('4', 'Green'), ('9', 'Unknown'), ('2', 'Yellow')], max_length=3, db_column='tag_colour', verbose_name='Tag Colour', default='2', db_index=True),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('13', 'Ontario Hydro'), ('10', 'Lakehead University'), ('03', 'State of Michigan'), ('06', 'State of Ohio'), ('12', 'Private Club'), ('11', 'Sir Sandford Fleming College'), ('07', 'State of Pennsylvania'), ('05', 'University of Toronto'), ('24', 'CORA'), ('20', 'USGS'), ('19', 'USWFW'), ('01', 'Ontario Ministry of Natural Resources'), ('02', 'New York State'), ('04', 'University of Guelph'), ('08', 'Royal Ontario Museum'), ('25', 'AOFRC'), ('09', 'State of Minnesota'), ('99', 'Unknown'), ('98', 'Other'), ('26', 'GLLFAS')], max_length=3, db_column='tag_origin', verbose_name='Tag Origin', default='01', db_index=True),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('5', 'Flesh of Back'), ('1', 'Anterior Dorsal'), ('2', 'Between Dorsal'), ('4', 'Abdominal Insertion'), ('3', 'Posterior Dorsal'), ('6', 'Jaw'), ('9', 'Unknown'), ('7', 'Snout'), ('8', 'Anal')], max_length=3, db_column='tag_position', verbose_name='Tag Position', default='1', db_index=True),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('7', 'Strip Vinyl  '), ('A', 'Internal (Radio)'), ('C', 'Cinch'), ('B', 'Metal Livestock'), ('4', 'Butt End Jaw '), ('P', 'PIT tag'), ('6', 'Coded Wire'), ('3', 'Circular Strap Jaw '), ('8', 'Secure Tie'), ('2', 'Tubular Vinyl'), ('1', 'Streamer'), ('5', 'Anchor')], max_length=3, db_column='tag_type', verbose_name='Tag Type', default='1', db_index=True),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='date_flag',
            field=models.IntegerField(verbose_name='Date Flag', default=1, choices=[(1, 'Reported'), (0, 'Unknown'), (2, 'Derived')]),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='latlon_flag',
            field=models.IntegerField(verbose_name='Spatial Flag', default=1, choices=[(1, 'Reported'), (0, 'Unknown'), (2, 'Derived')]),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, null=True, choices=[('9', 'Unknown'), ('3', 'Hermaphrodite'), ('2', 'Female'), ('1', 'Male')], max_length=3, verbose_name='Sex', default='9'),
        ),
        migrations.AlterField(
            model_name='recoveryletter',
            name='method',
            field=models.CharField(verbose_name='Generated By', max_length=30, choices=[('tfat_template', 'TFAT Template'), ('custom_letter', 'Custom Letter')], default='tfat_template'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_flag',
            field=models.IntegerField(verbose_name='Date Flag', default=1, choices=[(1, 'Reported'), (0, 'Unknown'), (2, 'Derived')]),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_format',
            field=models.CharField(verbose_name='Report Format', max_length=30, choices=[('letter', 'letter'), ('verbal', 'verbal'), ('other', 'other'), ('dcr', 'DCR'), ('e-mail', 'e-mail')], default='verbal'),
        ),
    ]
