# Generated by Django 2.2.10 on 2020-04-16 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('tfat', '0008_auto_20200415_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Species'),
        ),
        migrations.AddField(
            model_name='recovery',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='common.Species'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('9', 'Unknown'), ('3', 'Hermaphrodite')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('2', 'Yellow'), ('7', 'White'), ('3', 'Red'), ('1', 'Colourless'), ('4', 'Green'), ('9', 'Unknown'), ('5', 'Orange'), ('6', 'Silver')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('26', 'GLLFAS'), ('24', 'CORA'), ('19', 'USFWS'), ('25', 'AOFRC'), ('06', 'Ohio'), ('03', 'Mich.'), ('12', 'Priv'), ('04', 'UofG'), ('08', 'ROM'), ('05', 'UofT'), ('98', 'Other'), ('13', 'OntHydro'), ('10', 'Lakehead'), ('09', 'Minn.'), ('99', 'Unkn'), ('01', 'MNRF'), ('20', 'USGS'), ('02', 'NY'), ('07', 'Penn.'), ('11', 'SSFC')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('5', 'Flesh of Back'), ('2', 'Between Dorsal'), ('6', 'Jaw'), ('8', 'Anal'), ('1', 'Anterior Dorsal'), ('4', 'Abdominal Insertion'), ('3', 'Posterior Dorsal'), ('7', 'Snout'), ('9', 'Unknown')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('6', 'Coded Wire'), ('1', 'Streamer'), ('A', 'Internal (Radio)'), ('P', 'PIT tag'), ('7', 'Strip Vinyl  '), ('B', 'Metal Livestock'), ('5', 'Anchor'), ('4', 'Butt End Jaw '), ('8', 'Secure Tie'), ('3', 'Circular Strap Jaw '), ('2', 'Tubular Vinyl'), ('C', 'Cinch')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('9', 'Unknown'), ('3', 'Hermaphrodite')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='recoveryletter',
            name='method',
            field=models.CharField(choices=[('custom_letter', 'Custom Letter'), ('tfat_template', 'TFAT Template')], default='tfat_template', max_length=30, verbose_name='Generated By'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_format',
            field=models.CharField(choices=[('other', 'other'), ('verbal', 'verbal'), ('dcr', 'DCR'), ('e-mail', 'e-mail'), ('letter', 'letter')], default='verbal', max_length=30, verbose_name='Report Format'),
        ),
    ]
