# Generated by Django 2.2.10 on 2020-02-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfat', '0008_auto_20180918_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='sex',
            field=models.CharField(blank=True, choices=[('2', 'Female'), ('1', 'Male'), ('3', 'Hermaphrodite'), ('9', 'Unknown')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='tagid',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='tagstat',
            field=models.CharField(blank=True, choices=[('A', 'Applied'), ('C', 'Existed on Capture')], db_index=True, default='C', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('4', 'Green'), ('3', 'Red'), ('6', 'Silver'), ('7', 'White'), ('2', 'Yellow'), ('9', 'Unknown'), ('5', 'Orange'), ('1', 'Colourless')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('12', 'Private Club'), ('24', 'CORA'), ('25', 'AOFRC'), ('10', 'Lakehead University'), ('20', 'USGS'), ('04', 'University of Guelph'), ('98', 'Other'), ('11', 'Sir Sandford Fleming College'), ('99', 'Unknown'), ('09', 'State of Minnesota'), ('05', 'University of Toronto'), ('03', 'State of Michigan'), ('02', 'New York State'), ('26', 'GLLFAS'), ('19', 'USFWS'), ('01', 'Ontario Ministry of Natural Resources'), ('13', 'Ontario Hydro'), ('08', 'Royal Ontario Museum'), ('07', 'State of Pennsylvania'), ('06', 'State of Ohio')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('4', 'Abdominal Insertion'), ('5', 'Flesh of Back'), ('2', 'Between Dorsal'), ('3', 'Posterior Dorsal'), ('7', 'Snout'), ('9', 'Unknown'), ('6', 'Jaw'), ('1', 'Anterior Dorsal'), ('8', 'Anal')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('8', 'Secure Tie'), ('A', 'Internal (Radio)'), ('5', 'Anchor'), ('2', 'Tubular Vinyl'), ('7', 'Strip Vinyl  '), ('P', 'PIT tag'), ('1', 'Streamer'), ('3', 'Circular Strap Jaw '), ('B', 'Metal Livestock'), ('C', 'Cinch'), ('6', 'Coded Wire'), ('4', 'Butt End Jaw ')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='date_flag',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Reported'), (2, 'Derived')], default=1, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='latlon_flag',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Reported'), (2, 'Derived')], default=1, verbose_name='Spatial Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, choices=[('2', 'Female'), ('1', 'Male'), ('3', 'Hermaphrodite'), ('9', 'Unknown')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='tagid',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_flag',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Reported'), (2, 'Derived')], default=0, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_format',
            field=models.CharField(choices=[('verbal', 'verbal'), ('other', 'other'), ('letter', 'letter'), ('e-mail', 'e-mail'), ('dcr', 'DCR')], default='verbal', max_length=30, verbose_name='Report Format'),
        ),
    ]
