# Generated by Django 2.2.10 on 2020-02-19 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('tfat', '0009_auto_20200219_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lake',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Projects', to='common.Lake'),
        ),
        migrations.AddField(
            model_name='recovery',
            name='lake',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='common.Lake'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('3', 'Hermaphrodite'), ('9', 'Unknown'), ('2', 'Female')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='tagstat',
            field=models.CharField(blank=True, choices=[('C', 'Existed on Capture'), ('A', 'Applied')], db_index=True, default='C', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('7', 'White'), ('5', 'Orange'), ('9', 'Unknown'), ('2', 'Yellow'), ('4', 'Green'), ('3', 'Red'), ('1', 'Colourless'), ('6', 'Silver')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('24', 'CORA'), ('99', 'Unknown'), ('01', 'Ontario Ministry of Natural Resources'), ('20', 'USGS'), ('08', 'Royal Ontario Museum'), ('19', 'USFWS'), ('04', 'University of Guelph'), ('02', 'New York State'), ('06', 'State of Ohio'), ('09', 'State of Minnesota'), ('12', 'Private Club'), ('10', 'Lakehead University'), ('03', 'State of Michigan'), ('07', 'State of Pennsylvania'), ('98', 'Other'), ('05', 'University of Toronto'), ('25', 'AOFRC'), ('11', 'Sir Sandford Fleming College'), ('26', 'GLLFAS'), ('13', 'Ontario Hydro')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('9', 'Unknown'), ('8', 'Anal'), ('1', 'Anterior Dorsal'), ('5', 'Flesh of Back'), ('7', 'Snout'), ('2', 'Between Dorsal'), ('6', 'Jaw'), ('4', 'Abdominal Insertion'), ('3', 'Posterior Dorsal')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('3', 'Circular Strap Jaw '), ('1', 'Streamer'), ('C', 'Cinch'), ('5', 'Anchor'), ('P', 'PIT tag'), ('B', 'Metal Livestock'), ('A', 'Internal (Radio)'), ('7', 'Strip Vinyl  '), ('4', 'Butt End Jaw '), ('2', 'Tubular Vinyl'), ('8', 'Secure Tie'), ('6', 'Coded Wire')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='date_flag',
            field=models.IntegerField(choices=[(2, 'Derived'), (0, 'Unknown'), (1, 'Reported')], default=1, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='latlon_flag',
            field=models.IntegerField(choices=[(2, 'Derived'), (0, 'Unknown'), (1, 'Reported')], default=1, verbose_name='Spatial Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('3', 'Hermaphrodite'), ('9', 'Unknown'), ('2', 'Female')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='spc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='tfat.Species'),
        ),
        migrations.AlterField(
            model_name='recoveryletter',
            name='method',
            field=models.CharField(choices=[('custom_letter', 'Custom Letter'), ('tfat_template', 'TFAT Template')], default='tfat_template', max_length=30, verbose_name='Generated By'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_flag',
            field=models.IntegerField(choices=[(2, 'Derived'), (0, 'Unknown'), (1, 'Reported')], default=0, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_format',
            field=models.CharField(choices=[('other', 'other'), ('e-mail', 'e-mail'), ('letter', 'letter'), ('verbal', 'verbal'), ('dcr', 'DCR')], default='verbal', max_length=30, verbose_name='Report Format'),
        ),
    ]
