# Generated by Django 2.2.10 on 2020-04-16 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20200414_1700'),
        ('tfat', '0009_auto_20200415_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='sex',
            field=models.CharField(blank=True, choices=[('3', 'Hermaphrodite'), ('2', 'Female'), ('9', 'Unknown'), ('1', 'Male')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Species'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('5', 'Orange'), ('3', 'Red'), ('6', 'Silver'), ('7', 'White'), ('9', 'Unknown'), ('2', 'Yellow'), ('1', 'Colourless'), ('4', 'Green')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('98', 'Other'), ('04', 'UofG'), ('01', 'MNRF'), ('08', 'ROM'), ('13', 'OntHydro'), ('99', 'Unkn'), ('20', 'USGS'), ('25', 'AOFRC'), ('19', 'USFWS'), ('05', 'UofT'), ('03', 'Mich.'), ('09', 'Minn.'), ('26', 'GLLFAS'), ('10', 'Lakehead'), ('07', 'Penn.'), ('06', 'Ohio'), ('02', 'NY'), ('12', 'Priv'), ('24', 'CORA'), ('11', 'SSFC')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('1', 'Anterior Dorsal'), ('3', 'Posterior Dorsal'), ('2', 'Between Dorsal'), ('9', 'Unknown'), ('7', 'Snout'), ('8', 'Anal'), ('4', 'Abdominal Insertion'), ('6', 'Jaw'), ('5', 'Flesh of Back')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('5', 'Anchor'), ('C', 'Cinch'), ('3', 'Circular Strap Jaw '), ('6', 'Coded Wire'), ('A', 'Internal (Radio)'), ('4', 'Butt End Jaw '), ('7', 'Strip Vinyl  '), ('8', 'Secure Tie'), ('P', 'PIT tag'), ('B', 'Metal Livestock'), ('2', 'Tubular Vinyl'), ('1', 'Streamer')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='date_flag',
            field=models.IntegerField(choices=[(0, 'Unknown'), (2, 'Derived'), (1, 'Reported')], default=1, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='latlon_flag',
            field=models.IntegerField(choices=[(0, 'Unknown'), (2, 'Derived'), (1, 'Reported')], default=1, verbose_name='Spatial Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, choices=[('3', 'Hermaphrodite'), ('2', 'Female'), ('9', 'Unknown'), ('1', 'Male')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='common.Species'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_flag',
            field=models.IntegerField(choices=[(0, 'Unknown'), (2, 'Derived'), (1, 'Reported')], default=0, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_format',
            field=models.CharField(choices=[('other', 'other'), ('dcr', 'DCR'), ('verbal', 'verbal'), ('e-mail', 'e-mail'), ('letter', 'letter')], default='verbal', max_length=30, verbose_name='Report Format'),
        ),
        migrations.AlterIndexTogether(
            name='encounter',
            index_together={('tagid', 'tagdoc', 'species')},
        ),
        migrations.AlterIndexTogether(
            name='recovery',
            index_together={('tagid', 'tagdoc', 'species')},
        ),
    ]
