# Generated by Django 2.2.10 on 2020-04-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfat', '0010_auto_20200415_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='spc',
        ),
        migrations.RemoveField(
            model_name='recovery',
            name='spc',
        ),
        migrations.AlterField(
            model_name='encounter',
            name='sex',
            field=models.CharField(blank=True, choices=[('3', 'Hermaphrodite'), ('9', 'Unknown'), ('1', 'Male'), ('2', 'Female')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='tagstat',
            field=models.CharField(blank=True, choices=[('A', 'Applied'), ('C', 'Existed on Capture')], db_index=True, default='C', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('3', 'Red'), ('2', 'Yellow'), ('6', 'Silver'), ('9', 'Unknown'), ('1', 'Colourless'), ('5', 'Orange'), ('7', 'White'), ('4', 'Green')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('11', 'SSFC'), ('20', 'USGS'), ('08', 'ROM'), ('24', 'CORA'), ('04', 'UofG'), ('12', 'Priv'), ('99', 'Unkn'), ('03', 'Mich.'), ('07', 'Penn.'), ('19', 'USFWS'), ('09', 'Minn.'), ('05', 'UofT'), ('01', 'MNRF'), ('06', 'Ohio'), ('98', 'Other'), ('10', 'Lakehead'), ('13', 'OntHydro'), ('26', 'GLLFAS'), ('25', 'AOFRC'), ('02', 'NY')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('2', 'Between Dorsal'), ('7', 'Snout'), ('6', 'Jaw'), ('9', 'Unknown'), ('8', 'Anal'), ('1', 'Anterior Dorsal'), ('5', 'Flesh of Back'), ('3', 'Posterior Dorsal'), ('4', 'Abdominal Insertion')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('5', 'Anchor'), ('7', 'Strip Vinyl  '), ('6', 'Coded Wire'), ('3', 'Circular Strap Jaw '), ('4', 'Butt End Jaw '), ('2', 'Tubular Vinyl'), ('B', 'Metal Livestock'), ('8', 'Secure Tie'), ('C', 'Cinch'), ('A', 'Internal (Radio)'), ('1', 'Streamer'), ('P', 'PIT tag')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='date_flag',
            field=models.IntegerField(choices=[(2, 'Derived'), (1, 'Reported'), (0, 'Unknown')], default=1, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='latlon_flag',
            field=models.IntegerField(choices=[(2, 'Derived'), (1, 'Reported'), (0, 'Unknown')], default=1, verbose_name='Spatial Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, choices=[('3', 'Hermaphrodite'), ('9', 'Unknown'), ('1', 'Male'), ('2', 'Female')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_flag',
            field=models.IntegerField(choices=[(2, 'Derived'), (1, 'Reported'), (0, 'Unknown')], default=0, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_format',
            field=models.CharField(choices=[('verbal', 'verbal'), ('letter', 'letter'), ('e-mail', 'e-mail'), ('other', 'other'), ('dcr', 'DCR')], default='verbal', max_length=30, verbose_name='Report Format'),
        ),
    ]
