# Generated by Django 2.2.10 on 2020-04-16 14:12

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20200414_1700'),
        ('tfat', '0012_auto_20200415_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedSpecies',
            fields=[
                ('species_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.Species')),
                ('tagged', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['spc_nmco'],
            },
            bases=('common.species',),
            managers=[
                ('all_species', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='encounter',
            name='sex',
            field=models.CharField(blank=True, choices=[('9', 'Unknown'), ('3', 'Hermaphrodite'), ('2', 'Female'), ('1', 'Male')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('1', 'Colourless'), ('3', 'Red'), ('9', 'Unknown'), ('6', 'Silver'), ('4', 'Green'), ('2', 'Yellow'), ('5', 'Orange'), ('7', 'White')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('09', 'Minn.'), ('10', 'Lakehead'), ('98', 'Other'), ('13', 'OntHydro'), ('03', 'Mich.'), ('08', 'ROM'), ('24', 'CORA'), ('99', 'Unkn'), ('19', 'USFWS'), ('25', 'AOFRC'), ('12', 'Priv'), ('05', 'UofT'), ('07', 'Penn.'), ('02', 'NY'), ('04', 'UofG'), ('11', 'SSFC'), ('26', 'GLLFAS'), ('01', 'MNRF'), ('20', 'USGS'), ('06', 'Ohio')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('6', 'Jaw'), ('9', 'Unknown'), ('2', 'Between Dorsal'), ('5', 'Flesh of Back'), ('3', 'Posterior Dorsal'), ('4', 'Abdominal Insertion'), ('7', 'Snout'), ('8', 'Anal'), ('1', 'Anterior Dorsal')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('A', 'Internal (Radio)'), ('B', 'Metal Livestock'), ('6', 'Coded Wire'), ('3', 'Circular Strap Jaw '), ('P', 'PIT tag'), ('1', 'Streamer'), ('5', 'Anchor'), ('C', 'Cinch'), ('2', 'Tubular Vinyl'), ('8', 'Secure Tie'), ('4', 'Butt End Jaw '), ('7', 'Strip Vinyl  ')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='date_flag',
            field=models.IntegerField(choices=[(1, 'Reported'), (2, 'Derived'), (0, 'Unknown')], default=1, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='latlon_flag',
            field=models.IntegerField(choices=[(1, 'Reported'), (2, 'Derived'), (0, 'Unknown')], default=1, verbose_name='Spatial Flag'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, choices=[('9', 'Unknown'), ('3', 'Hermaphrodite'), ('2', 'Female'), ('1', 'Male')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='recoveryletter',
            name='method',
            field=models.CharField(choices=[('tfat_template', 'TFAT Template'), ('custom_letter', 'Custom Letter')], default='tfat_template', max_length=30, verbose_name='Generated By'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_flag',
            field=models.IntegerField(choices=[(1, 'Reported'), (2, 'Derived'), (0, 'Unknown')], default=0, verbose_name='Date Flag'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_format',
            field=models.CharField(choices=[('e-mail', 'e-mail'), ('verbal', 'verbal'), ('letter', 'letter'), ('other', 'other'), ('dcr', 'DCR')], default='verbal', max_length=30, verbose_name='Report Format'),
        ),
    ]
