# Generated by Django 2.2.10 on 2020-04-16 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tfat', '0013_auto_20200416_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='sex',
            field=models.CharField(blank=True, choices=[('9', 'Unknown'), ('3', 'Hermaphrodite'), ('1', 'Male'), ('2', 'Female')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfat.TaggedSpecies'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_colour',
            field=models.CharField(choices=[('3', 'Red'), ('6', 'Silver'), ('9', 'Unknown'), ('2', 'Yellow'), ('7', 'White'), ('1', 'Colourless'), ('4', 'Green'), ('5', 'Orange')], db_column='tag_colour', db_index=True, default='2', max_length=3, verbose_name='Tag Colour'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_origin',
            field=models.CharField(choices=[('12', 'Priv'), ('09', 'Minn.'), ('06', 'Ohio'), ('13', 'OntHydro'), ('24', 'CORA'), ('11', 'SSFC'), ('04', 'UofG'), ('08', 'ROM'), ('05', 'UofT'), ('99', 'Unkn'), ('20', 'USGS'), ('10', 'Lakehead'), ('07', 'Penn.'), ('01', 'MNRF'), ('02', 'NY'), ('26', 'GLLFAS'), ('98', 'Other'), ('19', 'USFWS'), ('25', 'AOFRC'), ('03', 'Mich.')], db_column='tag_origin', db_index=True, default='01', max_length=3, verbose_name='Tag Origin'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_position',
            field=models.CharField(choices=[('8', 'Anal'), ('9', 'Unknown'), ('7', 'Snout'), ('2', 'Between Dorsal'), ('5', 'Flesh of Back'), ('4', 'Abdominal Insertion'), ('6', 'Jaw'), ('1', 'Anterior Dorsal'), ('3', 'Posterior Dorsal')], db_column='tag_position', db_index=True, default='1', max_length=3, verbose_name='Tag Position'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='_tag_type',
            field=models.CharField(choices=[('3', 'Circular Strap Jaw '), ('P', 'PIT tag'), ('A', 'Internal (Radio)'), ('C', 'Cinch'), ('1', 'Streamer'), ('7', 'Strip Vinyl  '), ('8', 'Secure Tie'), ('4', 'Butt End Jaw '), ('2', 'Tubular Vinyl'), ('6', 'Coded Wire'), ('B', 'Metal Livestock'), ('5', 'Anchor')], db_column='tag_type', db_index=True, default='1', max_length=3, verbose_name='Tag Type'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, choices=[('9', 'Unknown'), ('3', 'Hermaphrodite'), ('1', 'Male'), ('2', 'Female')], default='9', max_length=3, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='tfat.TaggedSpecies'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_format',
            field=models.CharField(choices=[('letter', 'letter'), ('verbal', 'verbal'), ('other', 'other'), ('e-mail', 'e-mail'), ('dcr', 'DCR')], default='verbal', max_length=30, verbose_name='Report Format'),
        ),
    ]
